// generated by gostdev.
// DO NOT CHANGE THIS FILE!

package main

import "net/http"

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

var (
	indexRoute = Route{
		"Index",
		"GET",
		"/",
		Index,
	}

	operationRoutes = Routes{
		{{range $key, $function := .}}
			{{ range $oneCommentLine := split $function.Description }}
			// {{ $oneCommentLine }}	{{ end }}
			Route{
				"{{ $function.Name }}",
				"{{ $function.Method }}",
				"{{ $function.Uri }}",
				{{ $function.Name }},
			},
		{{ end }}
	}
)
